### ISSUE TITLE
KeyError: 'attachments'

### ISSUE THREAD

**Issue by frmkkl** [Aragroth/repost-vk-2-tg#3]
Добрый день.
Очень сильно за интересовал ваш проект!Но к сожалению возникла одна проблема которую я не могу решить. Установив все по инструкции все относительно работало. Если я постил фото или видео и запускал скрипт, то он отсылал в ТГ паблик фото\видео, но потом сразу же выдавал ошибку : 

```
  File "D:\Bot\repost-vk-2-tg-master\models\post_creator.py", line 80, in parse_attachments
    for element in self.raw_post['attachments']:
KeyError: 'attachments'

```
И чтобы снова получить желаемый результат необходимо снова запустить скрипт, но каждый раз вылетает с этой ошибкой. Можно ли как-то это исправить? Буду благодарен за любую помощь!

И я бы хотел уточнить у Вас еще один момент, а именно при отправке двух разных видео он загружал в ТГ два одинаковых первых видео.
Так же если отправить просто фото без текста, то он выдает ошибку : 

```
D:\Bot\repost-vk-2-tg-master>python main.py
Traceback (most recent call last):
  File "D:\Bot\repost-vk-2-tg-master\main.py", line 29, in <module>
    telegram_sender.send_post_as_messages(post)
  File "D:\Bot\repost-vk-2-tg-master\models\sender.py", line 38, in send_post_as_messages
    self.send_with_no_text()
  File "D:\Bot\repost-vk-2-tg-master\models\sender.py", line 169, in send_with_no_text
    InputMediaPhoto(file[PHOTO]) if PHOTO in file.keys()[0] else InputMediaVideo(
TypeError: 'dict_keys' object is not subscriptable

```

Я буду очень благодарен если будет возможность исправить эти исключения.
Спасибо!

**Comment by Aragroth** [comment]
По-идее исправил баг с attachments и если фото без текста. Касательно загрузки одинаковых видео посмотрю позже

**Comment by frmkkl** [comment]
@Aragroth, Спасибо огромное!
